# Generated by Django 4.1.2 on 2022-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voices',
            fields=[
                ('id_no', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('voice_name', models.TextField(max_length=40)),
            ],
        ),
    ]
