# Generated by Django 4.1.1 on 2022-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('language_name', models.TextField(max_length=100)),
            ],
        ),
    ]
