# Generated by Django 4.1.1 on 2022-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesmodel',
            name='id_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
